trigger:
  branches:
    include:
      - DEV # goes to DEV environment

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 7.X"
            inputs:
              packageType:"sdk"
              version:"7.x"
          
          - script: dotnet restore
            displayName: "dotnet restore"

          - script: dotnet publish --configuration $(buildConfiguration)
            displayName: "dotnet publish --configuration $(buildConfiguration)"
