trigger:
  branches:
    include:
      - DEV # goes to DEV environment

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 7.X"
            inputs:
              packageType: 'sdk'  # Corrected indentation and added single quotes
              version: '7.x'     # Corrected indentation and added single quotes
          
          - script: dotnet restore
            displayName: "dotnet restore"

          - script: dotnet publish --configuration $(buildConfiguration)
            displayName: "dotnet publish --configuration $(buildConfiguration)"